*** Variables ***
${LOGIN_EMAIL_FORM}            id=login-email-input
${LOGIN_PASSWORD_FORM}         id=login-password-input
${LOGIN_PASSWORD_VISIBLE}      xpath=//*[@id="root"]/div[1]/div[1]/div/form/div/div/button
${LOGIN_SUBMIT_BUTTON}         xpath=//*[@id="root"]/div[1]/div[1]/div/form/div/button
${FORGOT_PASSWORD_LINK}        xpath=//a[@class='leading-4 text-xs text-primary-normal cursor-pointer select-none']