*** Variables ***
&{POSITION}
...    SOFTWARE_DEVELOPER=e40e3073-3a47-4008-a9c6-a6d3c84572d9
...    PRODUCT_MANAGER=d7012dff-9efa-4861-86ba-0f5c15882a1a
...    UI_UX_DESIGNER=f2ee9eff-13da-487b-b633-5237940ceb90
...    BUSINESS_ANALYST=0cbea1bc-3071-4908-984b-8d54c3a16342
...    DATA_ANALYST=1097694d-b05e-4550-b033-3e034d5c1bf2
...    DATA_SCIENTIST=d6c2ee5c-6248-4045-96a7-41175d7b4c7a
...    HUMAN_RESOURCE=13a99e06-0696-4246-8dd6-2f7d79dd3336

&{ROLE}
...    HR=5face0e0-96ea-48f8-bc45-964758fa74cd
...    STAFF=f903222f-3815-4119-8605-9e0724e63ba6
...    MANAGER=6e2908fd-112b-4b6d-9c7f-152b7f7fe849

&{NEW_EMPLOYEE}
...    full_name=Barry Jane
...    birth_date=2001-01-01
...    email=sinarlog-staff90@yopmail.com
...    phone=111111111990
...    address=Chase Plaza, Jl. Jenderal Sudirman No.21, RT.10/RW.1, Kuningan, Karet, Kecamatan Setiabudi, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12920
...    gender=Female
...    marital_status=Single
...    npwp=111111111111990
...    religion=Muslim
...    nik=1111110101010990
...    employment_type=Full Time
...    position=Software Developer
...    role=Staff
...    manager=0569374e-da8f-463d-88e8-970673b6841a
...    contact_name=Automation Contact
...    contact_phone=811111000099
...    contact_relation=Spouse